Models/Familiar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fincas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familiar
    {
        public int codigo { get; set; }
        public Nullable<int> codigo_persona { get; set; }
        public Nullable<int> codigo_familiar { get; set; }
        public string parentesco { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}

Controllers/FamiliarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fincas.Models;

namespace Fincas.Controllers
{
    public class FamiliarController : Controller
    {
        private fincasEntities db = new fincasEntities();

        // GET: Personas
        public ActionResult AdministrarFamiliares(int idPersona,int idFinca)
        {
            List<Familiar> familiares = db.Familiars.Where(f => f.codigo_persona == idPersona).ToList();
            List<Persona> personas = new List<Persona>();
            List<String> parentescos = new List<String>();
            foreach (Familiar item in familiares)
            {
                personas.Add(db.Personas.Find(item.codigo_familiar));
                parentescos.Add(item.parentesco);
            }
            ViewBag.idPersona = idPersona;
            ViewBag.parentescos = parentescos;
            ViewBag.idFinca = idFinca;
            return View("Index", personas);
        }
  
        // GET: Personas/Details/5
        public ActionResult Details(int? id,int idPersona,String parentesco)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.idPersona = idPersona;
            ViewBag.parentesco = parentesco;
            return View(persona);
        }

        // GET: Personas/Create
        public ActionResult Create(int idPersona)
        {
            ViewBag.idPersona = idPersona;
            return View();
        }

        // POST: Personas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codigo,tipo_identificacion,numero_identificacion,nombre,rol")] Persona persona,int idPersona,String parentesco)
        {
            if (ModelState.IsValid)
            {
                Familiar familiar = new Familiar();
                familiar.codigo_persona= idPersona;
                familiar.codigo_familiar = persona.codigo;
                familiar.parentesco = parentesco;
                db.Familiars.Add(familiar);
                db.Personas.Add(persona);
                db.SaveChanges();
                return RedirectToAction("AdministrarFamiliares", new { idPersona = idPersona });
            }

            return View(persona);
        }

        // GET: Personas/Edit/5
        public ActionResult Edit(int? id,int idPersona,String parentesco)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.idPersona = idPersona;
            ViewBag.parentesco = parentesco;
            return View(persona);
        }

        // POST: Personas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codigo,tipo_identificacion,numero_identificacion,nombre,rol")] Persona persona,int idPersona)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persona).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdministrarFamiliares", new { idPersona = idPersona });
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public ActionResult Delete(int? id,int idPersona,String parentesco)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.idPersona = idPersona;
            ViewBag.parentesco = parentesco;
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idPersona)
        {
            Familiar familiar = db.Familiars.Where(f => f.codigo_familiar == id).Where(f => f.codigo_persona == idPersona).First();
            db.Familiars.Remove(familiar);
            Persona persona = db.Personas.Find(id);
            db.Personas.Remove(persona);
            db.SaveChanges();
            return RedirectToAction("AdministrarFamiliares", new { idPersona = idPersona });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fincas.Models;

namespace Fincas.Controllers
{
    public class PersonasController : Controller
    {
        private fincasEntities db = new fincasEntities();

        // GET: Personas
        public ActionResult Index()
        {
            return View(db.Personas.ToList());
        }
        public ActionResult AdministrarPorFinca(int idFinca)
        {
           List<Finca_Persona> fincaPersonas = db.Finca_Persona.Where(p => p.codigo_finca == idFinca).ToList();
            List<Persona> personas = new List<Persona>();
            foreach(Finca_Persona item in fincaPersonas)
            {
                personas.Add(db.Personas.Find(item.codigo_persona));
            }
            ViewBag.idFinca = idFinca;
            return View("Index",personas);
        }
        
        // GET: Personas/Details/5
        public ActionResult Details(int? id, int idFinca)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.idFinca = idFinca;
            return View(persona);
        }

        // GET: Personas/Create
        public ActionResult Create(int? idFinca)
        {
            ViewBag.idFinca = idFinca;
            return View();
        }

        // POST: Personas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codigo,tipo_identificacion,numero_identificacion,nombre,rol")] Persona persona,int idFinca)
        {
            if (ModelState.IsValid)
            {
                Finca_Persona fincaPersona = new Finca_Persona();
                fincaPersona.codigo_finca = idFinca;
                fincaPersona.codigo_persona = persona.codigo;
                db.Finca_Persona.Add(fincaPersona);
                db.Personas.Add(persona);
                db.SaveChanges();
                return RedirectToAction("AdministrarPorFinca", new { idFinca = idFinca });
            }

            return View(persona);
        }

        // GET: Personas/Edit/5
        public ActionResult Edit(int? id,int idFinca)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.idFinca = idFinca;
            return View(persona);
        }

        // POST: Personas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codigo,tipo_identificacion,numero_identificacion,nombre,rol")] Persona persona,int idFinca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persona).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdministrarPorFinca", new { idFinca = idFinca });
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public ActionResult Delete(int? id,int idFinca)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.idFinca = idFinca;
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idFinca)
        {
            Finca_Persona fincaPersona = db.Finca_Persona.Where(fp => fp.codigo_finca == idFinca).Where(fp => fp.codigo_persona == id).First();
            db.Finca_Persona.Remove(fincaPersona);
            Persona persona = db.Personas.Find(id);
            db.Personas.Remove(persona);
            db.SaveChanges();
            return RedirectToAction("AdministrarPorFinca", new { idFinca = idFinca });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Familiar/Create.cshtml
@model Fincas.Models.Persona

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Persona   </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("tipo de identificacion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.tipo_identificacion, new SelectList(new List<Object> { "TI", "CC" }), new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tipo_identificacion, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.Label("numero de identificacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero_identificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero_identificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Parentesco", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("parentesco", new SelectList(new List<Object> { "Esposo(a)", "Hijo(a)", "Hermano(a)","Sobrino(a)" }), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("Parentesco", "", new { @class = "text-danger" })
            </div>
        </div>
        <input id="rol"
               name="rol"
               type="hidden"
               value="Familiar" />
        <input id="idPersona"
               name="idPersona"
               type="hidden"
               value=@ViewBag.idPersona />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "AdministrarFamiliares", new { idPersona = ViewBag.idPersona })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Familiar/Delete.cshtml
@model Fincas.Models.Persona

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Esta seguro que desea eliminar esta persona?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("tipo de identificacion")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_identificacion)
        </dd>

        <dt>
            @Html.DisplayName("numero de identificacion")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero_identificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayName("Parentesco")
        </dt>

        <dd>
            @ViewBag.parentesco
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input id="idPersona"
               name="idPersona"
               type="hidden"
               value=@ViewBag.idPersona />
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver", "AdministrarFamiliares", new { idPersona = ViewBag.idPersona })
        </div>
    }
</div>

Views/Familiar/Details.cshtml
@model Fincas.Models.Persona

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("tipo de identificacion")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_identificacion)
        </dd>

        <dt>
            @Html.DisplayName("numero de identificacion")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero_identificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayName("Parentesco")
        </dt>

        <dd>
            @ViewBag.parentesco
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Volver", "AdministrarFamiliares", new { idPersona = ViewBag.idPersona })
</p>

Views/Familiar/Edit.cshtml
@model Fincas.Models.Persona

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.codigo)

    <div class="form-group">
        @Html.Label("tipo de identificacion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.tipo_identificacion, new SelectList(new List<Object> { "TI", "CC" }), new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tipo_identificacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("numero de identificacion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.numero_identificacion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numero_identificacion, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "AdministrarFamiliares", new { idPersona = ViewBag.idPersona })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Familiar/Index.cshtml
@model IEnumerable<Fincas.Models.Persona>

@{
    ViewBag.Title = "Familiares";
}

<h2>Familiares</h2>

<p>
    @Html.ActionLink("Agregar", "Create", new { idPersona = @ViewBag.idPersona })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("tipo de identificacion")
        </th>
        <th>
            @Html.DisplayName("numero de identificacion")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayName("parentesco")
        </th>
        <th></th>
    </tr>

    @for (var i = 0; i < Model.Count(); i++)
    {
        var item = Model.ElementAt(i);
        var parentesco = ViewBag.parentescos[i];
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tipo_identificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numero_identificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @parentesco
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.codigo, idPersona = ViewBag.idPersona,parentesco=parentesco }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.codigo, idPersona = ViewBag.idPersona,parentesco=parentesco }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.codigo, idPersona = ViewBag.idPersona, parentesco = parentesco })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Volver", "AdministrarPorFinca","Personas", new { idFinca = ViewBag.idFinca },null)